variables:
- group: 'jellyfin'

trigger:
  batch: true
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

pr:
  branches:
    include:
    - '*'

jobs:
  - job: Build
    displayName: 'Build'

    strategy:
      matrix:
        Debug:
          BuildConfiguration: debug
          ArtifactSuffix: debug
        Release:
          BuildConfiguration: release
          ArtifactSuffix: release
        Libre:
          BuildConfiguration: release
          ArtifactSuffix: libre

    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - script: 'echo "##vso[task.setvariable variable=NODE_ENV]development"'
      displayName: 'Set Node Variable'
      condition: eq(variables['BuildConfiguration'], 'debug')

    - script: 'echo "##vso[task.setvariable variable=TAG]$(git describe --tags)"'
      displayName: 'Set Tag Variable'

    - task: NodeTool@0
      displayName: 'Install Node'
      inputs:
        versionSpec: '12.x'

    - task: Cache@2
      displayName: 'Check Cache'
      inputs:
        key: 'npm | package-lock.json'
        path: 'node_modules'
        cacheHitVar: CACHE_RESTORED

    - script: 'npm ci'
      displayName: 'Install Dependencies'
      condition: ne(variables.CACHE_RESTORED, 'true')

    - script: 'npx cordova prepare'
      displayName: 'Prepare Cordova'

    - script: 'npx cordova build android --debug'
      displayName: 'Build Debug'
      condition: eq(variables['BuildConfiguration'], 'debug')

    - script: 'npx cordova plugin rm cordova-plugin-chromecast'
      displayName: 'Remove Play Services'
      condition: eq(variables['ArtifactSuffix'], 'libre')

    - script: 'npx cordova build android --release'
      displayName: 'Build Release'
      condition: eq(variables['BuildConfiguration'], 'release')

    - task: CopyFiles@2
      displayName: 'Copy APK'
      inputs:
        sourceFolder: 'platforms/android/app/build/outputs/apk'
        contents: '**/*.apk'
        targetFolder: '$(Build.ArtifactStagingDirectory)'
        flattenFolders: true

    - task: Bash@3
      displayName: 'Rename APK'
      inputs:
        targetType: 'inline'
        script: 'mv *.apk jellyfin-android-${ARTIFACTSUFFIX}-${TAG}.apk'
        workingDirectory: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish APK'
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'jellyfin-android-$(ArtifactSuffix)'
        publishLocation: 'Container'

  - job: Publish
    displayName: 'Publish'

    dependsOn: Build
    #condition: startsWith(variables['Build.SourceBranch'], 'refs/tags')

    strategy:
      matrix:
        Debug:
          BuildConfiguration: debug
          ArtifactSuffix: debug
        Release:
          BuildConfiguration: release
          ArtifactSuffix: release
        Libre:
          BuildConfiguration: release
          ArtifactSuffix: libre

    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - script: 'echo "##vso[task.setvariable variable=TAG]$(git describe --tags)"'
      displayName: 'Set Tag Variable'

    - task: DownloadPipelineArtifact@2
      displayName: 'Download APK'
      inputs:
        source: 'current'
        artifact: 'jellyfin-android-$(ArtifactSuffix)'
        path: '$(System.ArtifactsDirectory)'
        runVersion: 'latest'

    - task: DownloadSecureFile@1
      displayName: 'Download KeyStore'
      name: 'KeyStore'
      inputs:
        secureFile: 'keystore'

    - script: '$(find / -name apksigner -print -quit) sign --ks ${KEYSTORE_SECUREFILEPATH} --ks-pass pass:${PASSWORD} ${SYSTEM_ARTIFACTSDIRECTORY}/jellyfin-android-${ARTIFACTSUFFIX}-${TAG}'
      displayName: 'Sign APK'
      condition: eq(variables['BuildConfiguration'], 'release')
      env:
        PASSWORD: $(KeyStorePassword)

    #- task: GithubRelease@0
    #  displayName: 'GitHub Upload'
    #  inputs:
    #    gitHubConnection: Jellyfin Release Download
    #    repositoryName: jellyfin/jellyfin-android
    #    assets: '$(System.ArtifactsDirectory)/*.apk'
    #    action: 'edit'
    #    assetUploadMode: 'replace'
    #    tag: '$(TAG)'

    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: repository
        sourceFolder: '$(System.ArtifactsDirectory)'
        contents: '**'
        targetFolder: '/srv/repository/releases/client/android/versions/$(TAG)'

    - task: SSH@0
      inputs:
        sshEndpoint: repository
        runOptions: 'inline'
        inline: 'cd /srv/jellyfin/repository/releases/android && ln -s versions/$(TAG)/jellyfin-android-$(ArtifactSuffix)-$(TAG).apk .'
